[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=9.0.2"]

[project]
name = "smartp"
version = "0.1.0"
description = "Blocking test for all SMART capable drives on the system"
authors = [{name = "Jasper Chan", email = "jasperchan515@gmail.com"}]
requires-python = ">=3.10,<4"
readme = "README.md"
dependencies = ["pySMART"]

[project.scripts]
smartp = "smartp.main:main"

[tool.uv]

[tool.uv.sources]
pySMART = {git = "https://github.com/Gigahawk/py-SMART.git", branch = "polling_minutes"}
